code --install-extension 766b.go-outliner
code --install-extension banxi.go-snippets
code --install-extension bierner.markdown-preview-github-styles
code --install-extension christian-kohler.npm-intellisense
code --install-extension christian-kohler.path-intellisense
code --install-extension CoenraadS.bracket-pair-colorizer
code --install-extension dariofuzinato.vue-peek
code --install-extension DavidAnson.vscode-markdownlint
code --install-extension dbaeumer.vscode-eslint
code --install-extension donjayamanne.githistory
code --install-extension eamodio.gitlens
code --install-extension eg2.vscode-npm-script
code --install-extension esbenp.prettier-vscode
code --install-extension JohnyGeorges.jetjet-theme
code --install-extension mikestead.dotenv
code --install-extension ms-vscode.Go
code --install-extension msjsdiag.debugger-for-chrome
code --install-extension octref.vetur
code --install-extension PeterJausovec.vscode-docker
code --install-extension PKief.material-icon-theme
code --install-extension quicktype.quicktype
code --install-extension sdras.vue-vscode-snippets
code --install-extension streetsidesoftware.code-spell-checker
code --install-extension tombonnike.vscode-status-bar-format-toggle
code --install-extension WakaTime.vscode-wakatime
code --install-extension wesbos.theme-cobalt2
code --install-extension xabikos.JavaScriptSnippets
code --install-extension yzhang.markdown-all-in-one
